apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  annotations:
    strimzi.io/kraft: enabled
    strimzi.io/node-pools: enabled
  creationTimestamp: "2025-01-16T19:44:33Z"
  generation: 1
  name: platform-cluster
  namespace: streams-platform
  resourceVersion: "212181"
  uid: 677209bd-80bd-4f36-88db-abb130459c87
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    config:
      default.replication.factor: 3
      min.insync.replicas: 2
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
    listeners:
    - name: plain
      port: 9092
      tls: false
      type: internal
    - name: tls
      port: 9093
      tls: true
      type: internal
    metadataVersion: 3.8-IV0
    version: 3.8.0
status:
  clusterId: 3RCEf0yjShem64KlypycMQ
  conditions:
  - lastTransitionTime: "2025-01-17T14:23:31.800527954Z"
    status: "True"
    type: Ready
  kafkaMetadataState: KRaft
  kafkaMetadataVersion: 3.8-IV0
  kafkaNodePools:
  - name: broker-pool
  - name: controller-pool
  kafkaVersion: 3.8.0
  listeners:
  - addresses:
    - host: platform-cluster-kafka-bootstrap.streams-platform.svc
      port: 9092
    bootstrapServers: platform-cluster-kafka-bootstrap.streams-platform.svc:9092
    name: plain
  - addresses:
    - host: platform-cluster-kafka-bootstrap.streams-platform.svc
      port: 9093
    bootstrapServers: platform-cluster-kafka-bootstrap.streams-platform.svc:9093
    certificates:
    - |
      -----BEGIN CERTIFICATE-----
      MIIFLTCCAxWgAwIBAgIUP5vT2y77lrFft1H03T1K5oNFRnQwDQYJKoZIhvcNAQEN
      BQAwLTETMBEGA1UECgwKaW8uc3RyaW16aTEWMBQGA1UEAwwNY2x1c3Rlci1jYSB2
      MDAeFw0yNTAxMTYxOTQ0MzNaFw0yNjAxMTYxOTQ0MzNaMC0xEzARBgNVBAoMCmlv
      LnN0cmltemkxFjAUBgNVBAMMDWNsdXN0ZXItY2EgdjAwggIiMA0GCSqGSIb3DQEB
      AQUAA4ICDwAwggIKAoICAQC6u/60Mfk74lFuyLB3WDULMYtCgbuhMBAi9IEv66kO
      xikyBOju1cFcCjk0wIhlm0NeW90uoyzpF+odx0pwwtlpWy/i2eb/BA33Uzow65hb
      QztcDTS09jir4ztwJ0CxvbHnka9S8TF+rT2FEgR3gYws0H5k1wma2msqZU7KwUeY
      YI7GeLHLMuTjT3eml9hkEnLDCEMoBbJZd28VePXb+/rnHalguInSCmirAooSVGeb
      o6Jr+MuTwaOznb2G08Zol7s8SMs3Dyhs24tsymKkLfCN4E7p2CFxD4GCotzq97+2
      B+OzRY3m2bLIXntxNNb6tk4/6ZLHeM8w7kwY2HTBn+Pti2ZHIqgxQAACVRwb4oZR
      T8J479G5sUKTB/olNggfMQDI4J/huw+lunn1GWYAR7yUTyYo0O37XWZ46yq7d19s
      sA15hhBAsSltIx1l2gXh9quP2UcTxEMUGUgmKDuooU/INzhAZFLEMlB+TsjmnPV4
      s4DciNt2aOD8ojOmAK0okpAFQ9B05/r1ktcwOQa9HaZQzZlPyTBnYLnQfTH6JKs5
      N8/mr/nbDmYGKSMBJh/SCjX9SlYAPZN6VKtgYzN882Nbvxge7AzecmZa5LGh8R3p
      dieTQFBuw3qU0nnGdnnjnRm1ikqJTaTHhMwh+O2F/F6qM/KS1z28qp2TLdVIFR7d
      CwIDAQABo0UwQzAdBgNVHQ4EFgQUqcjjAGdUv4U+SqF1TLD1uNIdoFIwEgYDVR0T
      AQH/BAgwBgEB/wIBADAOBgNVHQ8BAf8EBAMCAQYwDQYJKoZIhvcNAQENBQADggIB
      AHOdEY+ZQHawtCBeultbAcd/Cgeo029KjlOLSKWwbB9phoqRLZwWIMiEWoOLpUez
      YO/cf2bvb1UWsSEbXOirEmoF1ZWYtgz2Jn4B/DT5YIzmCuh6GtQXeiPE2HYTi+me
      Ujx0HmJAZanjZpi8sAjEbPRkb6xCQI6aJwomGWOubBWE66NtvSyaAfTmI0wvKo2t
      LzrzpR8LIfzWWHQA+NX+SoK06Bk+QiFWuHnwW+ZXtF5ey2e+PjbS1QFLBiH7hrDJ
      esdJJ/5xo0IxdJuhFN6jkAYEcpzSfhOjuvfO7CgcJQ4ZCUqj9cPjIY1F9MOgAJXv
      57wP9xhkcWuO8FdzPujEP8N+jj5rq28cNLqY1YXFKRfXnEEZbFexh3QcNymay4Pu
      Evxo6VnBanH5PSmQFP3Mu2MyraYkpAo7xQ589BzOrFYJvLShRdtLpHMOJVBqfLbk
      AV3W6KEjkxdbmqexCKsxs8DrKPzvWycFff6aeTBBq//ybcs5HbqxgOrFnSC2H4BV
      f00dPfv3+ku8QoT3JINCI/I0bnAHiRyW0rqlNnAeSpBO0yDr59VRmGPJF203iVD4
      3PFy9UdmZoZ8P2pP1HWrQwPdTBm/R9PWPZ5gHpAyyz4rWSfzsNiI2YGC433zXrSq
      I2fv0xZs9Mqh4kI3VIx5AX1Nhnn3bLQWCqMMmd7sGdpj
      -----END CERTIFICATE-----
    name: tls
  observedGeneration: 1
  operatorLastSuccessfulVersion: 0.43.0.redhat-00005
  registeredNodeIds:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
