apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  annotations:
    strimzi.io/use-connector-resources: "true"
  creationTimestamp: "2025-01-16T20:14:06Z"
  generation: 3
  name: platform-connect-cluster
  namespace: streams-platform
  resourceVersion: "190800"
  uid: 333a49bc-75e4-4649-8c37-baa5aa355f09
spec:
  bootstrapServers: platform-cluster-kafka-bootstrap.streams-platform.svc:9093
  build:
    output:
      image: debezium-pgsql-streams-connect:latest
      type: imagestream
    plugins:
    - artifacts:
      - type: zip
        url: https://maven.repository.redhat.com/ga/io/debezium/debezium-connector-postgres/2.7.3.Final-redhat-00003/debezium-connector-postgres-2.7.3.Final-redhat-00003-plugin.zip
      - type: zip
        url: https://maven.repository.redhat.com/ga/io/debezium/debezium-scripting/2.7.3.Final-redhat-00003/debezium-scripting-2.7.3.Final-redhat-00003.zip
      - type: jar
        url: https://repo1.maven.org/maven2/org/apache/groovy/groovy/4.0.24/groovy-4.0.24.jar
      - type: jar
        url: https://repo1.maven.org/maven2/org/apache/groovy/groovy-jsr223/4.0.24/groovy-jsr223-4.0.24.jar
      - type: jar
        url: https://repo1.maven.org/maven2/org/apache/groovy/groovy-json/4.0.24/groovy-json-4.0.24.jar
      name: debezium-pgsql-connector
  config:
    config.storage.replication.factor: -1
    config.storage.topic: connect-cluster-configs
    group.id: connect-cluster
    offset.storage.replication.factor: -1
    offset.storage.topic: connect-cluster-offsets
    status.storage.replication.factor: -1
    status.storage.topic: connect-cluster-status
  replicas: 1
  tls:
    trustedCertificates:
    - pattern: '*.crt'
      secretName: platform-cluster-cluster-ca-cert
  version: 3.8.0
status:
  conditions:
  - lastTransitionTime: "2025-01-16T22:23:21.391254813Z"
    status: "True"
    type: Ready
  connectorPlugins:
  - class: io.debezium.connector.postgresql.PostgresConnector
    type: source
    version: 2.7.3.Final-redhat-00003
  - class: org.apache.kafka.connect.mirror.MirrorCheckpointConnector
    type: source
    version: 3.8.0.redhat-00007
  - class: org.apache.kafka.connect.mirror.MirrorHeartbeatConnector
    type: source
    version: 3.8.0.redhat-00007
  - class: org.apache.kafka.connect.mirror.MirrorSourceConnector
    type: source
    version: 3.8.0.redhat-00007
  labelSelector: strimzi.io/cluster=platform-connect-cluster,strimzi.io/name=platform-connect-cluster-connect,strimzi.io/kind=KafkaConnect
  observedGeneration: 3
  replicas: 1
  url: http://platform-connect-cluster-connect-api.streams-platform.svc:8083
