apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops
namePrefix: rtr-service-mesh-

resources:
- ../../default/base/
- ../../../applications/messaging/
- ../../../applications/cockroachdb/
- ../../../applications/edb/
- ../../../applications/service-mesh/
- ../../../applications/vault-secrets/

patches:
  - target:
      version: v1alpha1
      group: argoproj.io
      kind: Application
    patch: |-
      - op: replace
        path: /spec/project
        value: rtr-service-mesh-cluster-config
