---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: 5879af36f1f4ad1f7c3856e0eb7ef55d001ddf84
    app.quarkus.io/build-timestamp: 2022-11-04 - 04:12:52 +0000
  labels:
    app.kubernetes.io/name: demo-weather-in
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  name: demo-weather-in
  namespace: demo-weather-interface
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: 5879af36f1f4ad1f7c3856e0eb7ef55d001ddf84
    app.quarkus.io/build-timestamp: 2022-11-04 - 04:12:52 +0000
  labels:
    app.kubernetes.io/name: demo-weather-in
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  name: demo-weather-in
  namespace: demo-weather-interface
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: demo-weather-in
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: demo-weather-in
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: view-secrets
  namespace: demo-weather-interface
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: demo-weather-in
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: demo-weather-in-view
  namespace: demo-weather-interface
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: view
subjects:
  - kind: ServiceAccount
    name: demo-weather-in
    namespace: demo-weather-interface
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: demo-weather-in
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: demo-weather-in-view-secrets
  namespace: demo-weather-interface
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: view-secrets
subjects:
  - kind: ServiceAccount
    name: demo-weather-in
    namespace: demo-weather-interface
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: 5879af36f1f4ad1f7c3856e0eb7ef55d001ddf84
    app.quarkus.io/build-timestamp: 2022-11-04 - 04:12:52 +0000
  labels:
    app.kubernetes.io/name: demo-weather-in
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  name: demo-weather-in
  namespace: demo-weather-interface
spec: {}
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app.kubernetes.io/name: demo-weather-in
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: openjdk-17
  namespace: demo-weather-interface
spec:
  dockerImageRepository: registry.access.redhat.com/ubi8/openjdk-17
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: 5879af36f1f4ad1f7c3856e0eb7ef55d001ddf84
    app.quarkus.io/build-timestamp: 2022-11-04 - 04:12:52 +0000
  labels:
    app.kubernetes.io/name: demo-weather-in
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  name: demo-weather-in
  namespace: demo-weather-interface
spec:
  output:
    to:
      kind: ImageStreamTag
      name: demo-weather-in:1.0.0-SNAPSHOT
  source:
    binary: {}
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: openjdk-17:1.11
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/commit-id: 5879af36f1f4ad1f7c3856e0eb7ef55d001ddf84
    app.quarkus.io/build-timestamp: 2022-11-04 - 04:12:52 +0000
  labels:
    app.openshift.io/runtime: quarkus
    app.kubernetes.io/name: demo-weather-in
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: demo-weather-in
  namespace: demo-weather-interface
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: demo-weather-in
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      labels:
        app.openshift.io/runtime: quarkus
        app.kubernetes.io/name: demo-weather-in
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
    spec:
      containers:
        - command:
            - java
            - -Dquarkus.http.host=0.0.0.0
            - -Djava.util.logging.manager=org.jboss.logmanager.LogManager
            - -jar
            - /deployments/quarkus-run.jar
          env:
            - name: SMALLRYE_CONFIG_LOCATIONS
              value: /mnt/app-config-map
            - name: JAVA_APP_JAR
              value: /deployments/quarkus-run.jar
          image: image-registry.openshift-image-registry.svc:5000/demo-weather-interface/demo-weather-in:1.0.0-SNAPSHOT
          imagePullPolicy: Always
          name: demo-weather-in
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          volumeMounts:
            - mountPath: /mnt/app-config-map
              name: app-config-map
              readOnly: false
      serviceAccountName: demo-weather-in
      volumes:
        - configMap:
            name: demo-weather-in-config
            optional: false
          name: app-config-map
