apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: demo-weather-transform
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  name: demo-weather-transform
  namespace: demo-weather-interface
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: demo-weather-transform
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      labels:
        app.kubernetes.io/name: demo-weather-transform
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
        app.openshift.io/runtime: quarkus
    spec:
      containers:
        - command:
            - java
            - -Dquarkus.http.host=0.0.0.0
            - -Djava.util.logging.manager=org.jboss.logmanager.LogManager
            - -jar
            - /deployments/quarkus-run.jar
          env:
            - name: JAVA_APP_JAR
              value: /deployments/demo-weather-transform-1.0.0-SNAPSHOT-runner.jar
          image: image-registry.openshift-image-registry.svc:5000/demo-weather-interface/demo-weather-transform:1.0.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: demo-weather-transform
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 64Mi
