---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-weather-in-config
data:
  weather-station: kphx
  kafka-bootstrap-host: demo-weather-kafka-cluster-kafka-bootstrap.dev-demo-weather-interface.svc:9092
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: demo-weather-in
  labels:
    app.kubernetes.io/name: demo-weather-in
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/part-of: demo-weather-interface
    app.openshift.io/runtime: quarkus
spec:
  schedule: 0/5 * * * ?
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: demo-weather-in
            app.kubernetes.io/version: "1.0"
            app.openshift.io/runtime: quarkus
            app.kubernetes.io/part-of: demo-weather-interface
        spec:
          containers:
            - name: demo-weather-in
              image: image-registry.openshift-image-registry.svc:5000/demo-weather-interface/demo-weather-in:1.0
              envFrom:
                - configMapRef:
                    name: demo-weather-in-config
                    optional: false
              imagePullPolicy: IfNotPresent
              resources:
                limits:
                  cpu: 500m
                  memory: 256Mi
                requests:
                  cpu: 250m
                  memory: 128Mi
          restartPolicy: Never
          securityContext: {}
