apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app.kubernetes.io/name: demo-weather-in
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  name: demo-weather-in-job
  namespace: demo-weather-interface
spec:
  selector: {}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: demo-weather-in
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
        app.openshift.io/runtime: quarkus
    spec:
      containers:
        - command:
            - java
            - -Dquarkus.http.host=0.0.0.0
            - -Djava.util.logging.manager=org.jboss.logmanager.LogManager
            - -jar
            - /deployments/quarkus-run.jar
          env:
            - name: JAVA_APP_JAR
              value: /deployments/demo-weather-in-1.0.0-SNAPSHOT-runner.jar
            - name: WEATHER_STATION
              value: kdfw
          image: image-registry.openshift-image-registry.svc:5000/demo-weather-interface/demo-weather-in:1.0
          imagePullPolicy: IfNotPresent
          name: demo-weather-in
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 64Mi
      restartPolicy: Never
