namespace: rtr-app-cdb-operator
namePrefix: rtr-app-

resources:
- ../../../../manifests/cockroachdb/overlays/separate-operator-namespace

  # Set the OperatorGroup to watch the cdb namespace
patches:
- patch: |-
    - op: add
      path: /spec/targetNamespaces/0
      value: rtr-app-cdb
  target:
    group: operators.coreos.com
    kind: OperatorGroup
    name: cockroachdb-certified-og
    version: v1
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
