namespace: test-sit-rtr-in-mesh-edb
namePrefix: test-sit-rtr-in-mesh-

resources:
- ../../base
- OperatorGroup_cloud-native-postgresql.yaml
- ../../../../manifests/edb

patches:

  # Correct controller manager ConfigMap name to remove namePrefix
  - target:
      version: v1
      kind: ConfigMap
      name: postgresql-operator-controller-manager-config
    patch: |-
      - op: replace
        path: /metadata/name
        value: postgresql-operator-controller-manager-config
    options:
      allowNameChange: true

  # Set EDB namespace to be Service Mesh-enabled
  - target:
      group: project.openshift.io
      version: v1
      kind: Project
      name: edb
    patch: |-
      - op: add
        path: /metadata/labels/istio-injection
        value: enabled

  # Set the correct ServiceEntry hostnames
  - target:
      group: networking.istio.io
      version: v1beta1
      kind: ServiceEntry
      name: edb-cluster-operator-se
    patch: |-
      - op: add
        path: /spec/hosts/0
        value: "postgresql-operator-controller-manager-service.test-sit-rtr-in-mesh-edb-operator.svc"
