namespace: test-sit-rtr-in-mesh-cdb
namePrefix: test-sit-rtr-in-mesh-

resources:
- ../../base
- ../../../../manifests/cockroachdb

patches:
  - target:
      group: operators.coreos.com
      version: v1
      kind: Subscription
      name: cockroachdb-certified
    patch: |-
      - op: remove
        path: /metadata/namespace
  - target:
      group: operators.coreos.com
      version: v1
      kind: OperatorGroup
      name: cockroachdb-certified-og
    patch: |-
      - op: add
        path: /spec/targetNamespaces/0
        value: test-sit-rtr-in-mesh-cdb
  - target:
      group: networking.istio.io
      version: v1beta1
      kind: ServiceEntry
      name: cockroachdb-se
    patch: |-
      - op: add
        path: /spec/hosts/0
        value: "*.test-sit-rtr-in-mesh-cdb.test-sit-rtr-in-mesh-cdb.svc"
  - target:
      group: networking.istio.io
      version: v1beta1
      kind: DestinationRule
      name: cockroachdb-dr
    patch: |-
      - op: replace
        path: /spec/host
        value: "*.test-sit-rtr-in-mesh-cdb.test-sit-rtr-in-mesh-cdb.svc"
