namespace: test-sit-rtr-in-mesh-cdb
namePrefix: test-sit-rtr-in-mesh-

resources:
- ../../base

patches:

  # Set CDB namespace to be Service Mesh-enabled
  - target:
      group: project.openshift.io
      version: v1
      kind: Project
      name: cdb
    patch: |-
      - op: add
        path: /metadata/labels/istio-injection
        value: enabled

  # Set the correct ServiceEntry hostnames
  - target:
      group: networking.istio.io
      version: v1beta1
      kind: ServiceEntry
      name: cockroachdb-se
    patch: |-
      - op: add
        path: /spec/hosts/0
        value: "*.test-sit-rtr-in-mesh-cdb.test-sit-rtr-in-mesh-cdb.svc"
