apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- dev-demo-weather-interface-ns.yaml
- ../../base

namespace: dev-demo-weather-interface

commonLabels:
  variant: DEV

images:
- name: image-registry.openshift-image-registry.svc:5000/demo-weather-interface/demo-weather-in:1.0.0-SNAPSHOT
  newName: image-registry.openshift-image-registry.svc:5000/dev-demo-weather-interface/demo-weather-in
- name: image-registry.openshift-image-registry.svc:5000/demo-weather-interface/demo-weather-transform:1.0.0-SNAPSHOT
  newName: image-registry.openshift-image-registry.svc:5000/dev-demo-weather-interface/demo-weather-transform
