apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-config
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: app-config
  source:
    path: app-config/profiles/base
    repoURL: https://github.com/ryan-highley/integration-dev-demo-cluster-config
    # targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
