apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

resources:
- ../../../projects/
- ../../../applications/messaging/

patchesJson6902:
  - target:
      version: v1alpha1
      group: argoproj.io
      kind: Application
      name: '*'
    patch: |-
      - op: replace
        path: /spec/source/targetRevision
        value: reorg
