apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: cluster-ingress-gw
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 8000
      name: https
      protocol: HTTPS
    tls:
      mode: PASSTHROUGH
    hosts:
    - "rtr-app-edb/*"