apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: Pooler
metadata:
  name: cluster-pooler
  labels:
    app: rtr-service-mesh
    version: '1.0'
    openshift.io/cluster-monitoring: 'true'
spec:
  cluster: cluster

  template:
    metadata:
      labels:
        app: rtr-service-mesh
        version: '1.0'
        openshift.io/cluster-monitoring: 'true'
        service-mesh-name: basic
      annotations:
        sidecar.istio.io/inject: 'true'
        # traffic.sidecar.istio.io/includeInboundPorts: '5432'
        # traffic.sidecar.istio.io/excludeOutboundPorts: '*'
        # traffic.sidecar.istio.io/excludeOutboundIPRanges: '*'
        # traffic.sidecar.istio.io/excludeInboundPorts: '8000,9187'
        # traffic.sidecar.istio.io/excludeOutboundPorts: '9443,8080'
    spec:
      subdomain: edb

  pgbouncer: {}
