apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: edb-cluster-operator-se
spec:
  hosts:
  - "postgresql-operator-controller-manager-service.rtr-app-edb.svc"
  location: MESH_EXTERNAL
  ports:
  # - number: 8000
  #   name: https-8000
  #   protocol: HTTPS
  # - number: 9187
  #   name: https-9187
  #   protocol: HTTPS
  - number: 443
    name: https-443
    protocol: HTTPS
  - number: 9443
    name: https-9443
    protocol: HTTPS
  - number: 8080
    name: http-8080
    protocol: HTTP
  resolution: DNS
