namespace: openshift-gitops
namePrefix: camel-tahu-demo-
resources:
  - ../../base/
  - ../../../argocd/amq-broker/
  - ../../../argocd/streams-kafka/
patches:
  - target:
      version: v1alpha1
      group: argoproj.io
      kind: Application
    patch: |-
      - op: replace
        path: /spec/project
        value: camel-tahu-demo-cluster-config
  - target:
      version: v1alpha1
      group: argoproj.io
      kind: Application
      name: cluster-config
    patch: |-
      - op: replace
        path: /spec/source/path
        value: cluster-config/profiles/overlays/camel-tahu-demo
