apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

resources:
- ../../base/
- ../../../applications/messaging/
- ../../../applications/apicurio-registry/
- ../../../applications/cert-manager/
- ../../../applications/service-mesh/
- ../../../applications/sso/
- ../../../applications/vault-secrets/

patches:
  - target:
      version: v1alpha1
      group: argoproj.io
      kind: Application
      name: cluster-config
    patch: |-
      - op: replace
        path: /spec/source/path
        value: cluster-config/config/overlays/multi-tenant-kafka/
      - op: replace
        path: /metadata/name
        value: multi-tenant-kafka-cluster-config
