apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-app
spec:
  destination:
    namespace: streams-platform
    server: https://kubernetes.default.svc
  project: kafka
  source:
    path: apps/ignition/overlays/dev
    repoURL: https://github.com/ryan-highley/integration-dev-demo-cluster-config
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
