apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/cockroachdb-certified.openshift-operators: ''
  name: cockroachdb-certified
  namespace: cockroachdb
spec:
  channel: stable
  installPlanApproval: Automatic
  name: cockroachdb-certified
  source: certified-operators
  sourceNamespace: openshift-marketplace
