apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

resources:
- ../../base/
- ../../../applications/cluster-config/
- ../../../applications/messaging/
- ../../../applications/cockroachdb/
- ../../../applications/edb/
- ../../../applications/service-mesh/
- ../../../applications/vault-secrets/

patches:
  - target:
      version: v1alpha1
      group: argoproj.io
      kind: Application
      name: cluster-config
    patch: |-
      - op: replace
        path: /spec/source/path
        value: cluster-config/config/overlays/rtr-service-mesh/
      - op: replace
        path: /metadata/name
        value: rtr-service-mesh-cluster-config
