kind: Secret
apiVersion: v1
metadata:
  name: keycloak-db-secret
  labels:
    app: sso
stringData:
  POSTGRES_DATABASE: {{ pg_database }}
  POSTGRES_EXTERNAL_ADDRESS: {{ pg_address }}
  POSTGRES_EXTERNAL_PORT: "{{ pg_port }}"
  POSTGRES_PASSWORD: {{ pg_password }}
  POSTGRES_USERNAME: {{ pg_username }}
  POSTGRES_VERSION: "10"
  SSLMODE: require
type: Opaque
