apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  labels:
    app: sso
  name: rhsso
  namespace: rhsso
spec:
  externalAccess:
    enabled: true
  keycloakDeploymentSpec:
    imagePullPolicy: IfNotPresent
  postgresDeploymentSpec:
    imagePullPolicy: IIfNotPresent
  instances: 1
  disableReplicasSyncing: true
