apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sealed-secrets
resources:
- https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.17.5/controller.yaml
- namespace.yaml

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

patchesJson6902:
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: sealed-secrets-controller
    patch: |-
      - op: remove
        path: /spec/template/spec/containers/0/securityContext
      - op: remove
        path: /spec/template/spec/securityContext
