resources:
- Project_cdb-operator.yaml
- OperatorGroup_cockroachdb-certified-og.yaml
- ../../../manifests/cockroachdb

patches:
  # Set the OperatorGroup to install in the cdb-operator namespace but watch the cdb namespace
  - target:
      group: operators.coreos.com
      version: v1
      kind: OperatorGroup
      name: cockroachdb-certified-og
    patch: |-
      - op: add
        path: /spec/targetNamespaces/0
        value: rtr-app-cdb
