apiVersion: crdb.cockroachlabs.com/v1alpha1
kind: CrdbCluster
metadata:
  name: cdb
spec:
  dataStore:
    pvc:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "60Gi"
        volumeMode: Filesystem
  resources:
    requests:
      cpu: 500m
      memory: 2Gi
    limits:
      cpu: '2'
      memory: 8Gi
  tlsEnabled: true
  image:
    name: cockroachdb/cockroach:v24.2.3
  nodes: 3
  additionalLabels:
    sidecar.istio.io/inject: 'true'
  additionalAnnotations:
    traffic.sidecar.istio.io/excludeInboundPorts: '26258'
    traffic.sidecar.istio.io/excludeOutboundPorts: '26258'
