apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: cockroachdb-se
spec:
  hosts: []
  location: MESH_INTERNAL
  ports:
  - number: 26257
    name: sql
    protocol: TCP
  - number: 8080
    name: http
    protocol: HTTP
  resolution: NONE
