apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

patchesJson6902:
  - target:
      version: v1alpha1
      group: argoproj.io
      kind: Application
      name: 3scale-app
    path: patch-3scale-app.yaml
  - target:
      version: v1alpha1
      group: argoproj.io
      kind: Application
      name: demo-weather-interface-app
    path: patch-demo-weather-interface-app.yaml
