apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cockroachdb
spec:
  destination:
    namespace: streams-platform
    server: https://kubernetes.default.svc
  project: cockroachdb
  source:
    path: apps/cockroachdb/overlays/rtr-service-mesh
    repoURL: https://github.com/ryan-highley/integration-dev-demo-cluster-config
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
