apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: service-mesh
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: 'rtr-*'
    server: '*'
  - namespace: 'istio-system'
    server: '*'
  sourceRepos:
  - '*'
