namespace: rtr-app-edb
namePrefix: rtr-app-

resources:
- ../../base

patches:
  # - target:
  #     version: v1beta1
  #     group: networking.istio.io
  #     kind: VirtualService
  #     name: cluster-ingress-vs
  #   patch: |-
  #     - op: replace
  #       path: /spec/gateways/0
  #       value: rtr-app-cluster-ingress-gw
  - target:
      version: v1
      group: postgresql.k8s.enterprisedb.io
      kind: Pooler
      name: cluster-pooler
    patch: |-
      - op: replace
        path: /spec/cluster
        value: rtr-app-cluster
