namespace: rtr-app-edb
namePrefix: rtr-app-

resources:
- ../../base

patches:
  - target:
      version: v1beta1
      group: networking.istio.io
      kind: VirtualService
      name: cluster-ingress-vs
    patch: |-
      - op: replace
        path: /spec/gateways/0
        value: rtr-app-cluster-ingress-gw
