namespace: rtr-app-edb
namePrefix: rtr-app-

resources:
- ../../base
- ../../../../manifests/cockroachdb/OperatorGroup_cockroachdb.yaml
- ../../../../manifests/cockroachdb/Subscription_cockroachdb-certified.yaml

patches:
  # - target:
  #     version: v1beta1
  #     group: networking.istio.io
  #     kind: VirtualService
  #     name: cluster-ingress-vs
  #   patch: |-
  #     - op: replace
  #       path: /spec/gateways/0
  #       value: rtr-app-cluster-ingress-gw
  - target:
      group: operators.coreos.com
      version: v1
    patch: |-
      - op: remove
        path: /metadata/namespace
  - target:
      version: v1
      group: postgresql.k8s.enterprisedb.io
      kind: Pooler
      name: cluster-pooler
    patch: |-
      - op: replace
        path: /spec/cluster/name
        value: rtr-app-cluster
