namespace: openshift-gitops
namePrefix: multi-tenant-kafka-

resources:
- ../../default/base/
- ../../../applications/messaging/
- ../../../applications/apicurio-registry/
- ../../../applications/cert-manager/
- ../../../applications/service-mesh/
- ../../../applications/sso/
- ../../../applications/vault-secrets/

patches:
  - target:
      version: v1alpha1
      group: argoproj.io
      kind: Application
    patch: |-
      - op: replace
        path: /spec/project
        value: multi-tenant-kafka-cluster-config
