namespace: test-sit-rtr-in-mesh-cdb-client
namePrefix: test-sit-rtr-in-mesh-

resources:
- ../../base

patches:

  # Set CDB Client namespace to be Service Mesh-enabled
  - target:
      group: project.openshift.io
      version: v1
      kind: Project
      name: cdb
    patch: |-
      - op: add
        path: /metadata/labels/istio-injection
        value: enabled
