apiVersion: project.openshift.io/v1
kind: Project
metadata:
  name: tracing-system
  labels:
    kubernetes.io/metadata.name: tracing-system
    openshift.io/cluster-monitoring: "true"
    service-mesh-name: default
