namespace: openshift-gitops
namePrefix: rtr-service-mesh-
resources:
  - ../../base/
  - ../../../argocd/streams-kafka/
  - ../../../argocd/cockroachdb/
  - ../../../argocd/edb/
  - ../../../argocd/service-mesh/
  - ../../../argocd/vault-secrets/
patches:
  - target:
      version: v1alpha1
      group: argoproj.io
      kind: Application
    patch: |-
      - op: replace
        path: /spec/project
        value: rtr-service-mesh-cluster-config
  - target:
      version: v1alpha1
      group: argoproj.io
      kind: Application
      name: cluster-config
    patch: |-
      - op: replace
        path: /spec/source/path
        value: cluster-config/profiles/overlays/rtr-service-mesh
