apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-mesh
spec:
  destination:
    namespace: service-mesh
    server: https://kubernetes.default.svc
  project: service-mesh
  source:
    path: apps/service-mesh/base
    repoURL: https://github.com/ryan-highley/integration-dev-demo-cluster-config
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
