resources:
  - ../../base/
  - movies-app/
  - music-app/

patches:
  - target:
      version: v1alpha1
      group: argoproj.io
      kind: AppProject
      name: app-config
    patch: |-
      - op: replace
        path: /metadata/name
        value: multi-cluster-kafka-app-config
    options:
      allowNameChange: true
  - target:
      version: v1alpha1
      group: argoproj.io
      kind: Application
      name: app-config
    patch: |-
      - op: replace
        path: /spec/project
        value: multi-cluster-kafka-app-config
      - op: replace
        path: /spec/source/path
        value: app-config/profiles/overlays/multi-cluster-kafka
      - op: replace
        path: /metadata/name
        value: multi-cluster-kafka-app-config
    options:
      allowNameChange: true
  - target:
      version: v1alpha1
      group: argoproj.io
      kind: AppProject
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: openshift-gitops
  - target:
      version: v1alpha1
      group: argoproj.io
      kind: Application
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: openshift-gitops
