apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

resources:
- ../default/
- ../../../applications/messaging/

patches:
  - target:
      version: v1alpha1
      group: argoproj.io
      name: cluster-config
    patch: |-
      - op: replace
        path: /metadata/name
        value: camel-tahu-demo-cluster-config
  - target:
      version: v1alpha1
      group: argoproj.io
      kind: Application
    patch: |-
      - op: replace
        path: /spec/project
        value: camel-tahu-demo-cluster-config
      - op: replace
        path: /spec/source/path
        value: cluster-config/config/overlays/camel-tahu-demo/
