apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- htpass-auth.yaml
- rbac.yaml
- pipelines.yaml
- demo-weather-in-app.yaml
- demo-weather-transform-app.yaml
#- container-security-operator.yaml
#- sealed-secrets.yaml
