apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config-pipelines
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: manifests/pipelines/base
    repoURL: https://github.com/christianh814/openshift-cluster-config
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
