apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops
namePrefix: dev-

bases:
- ../../../applications/api-manager/
- ../../../applications/demo-weather-interface/

patchesJson6902:
  - target:
      version: v1alpha1
      group: argoproj.io
      kind: Application
      name: 3scale-app
    patch: |-
      - op: replace
        path: /spec/destination/namespace
        value: dev-3scale
      - op: replace
        path: /spec/project
        value: dev-api-manager
      - op: replace
        path: /spec/source/path
        value: apps/api-manager/overlays/dev
  - target:
      version: v1alpha1
      group: argoproj.io
      kind: Application
      name: demo-weather-interface-app
    patch: |-
      - op: replace
        path: /spec/destination/namespace
        value: dev-demo-weather-interface
      - op: replace
        path: /spec/project
        value: dev-demo-weather-interface
      - op: replace
        path: /spec/source/path
        value: apps/demo-weather-interface/overlays/dev
