apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ignition-platform-app
spec:
  destination:
    namespace: ignition-platform
    server: https://kubernetes.default.svc
  project: ignition-platform
  source:
    path: apps/ignition/overlays/dev
    repoURL: https://github.com/ryan-highley/integration-dev-demo-cluster-config
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
