namespace: openshift-gitops
namePrefix: multi-tenant-kafka-

resources:
  - ../../base/
  - ../../../argocd/rbac/
  - ../../../argocd/amq-broker/
  - ../../../argocd/streams-kafka/
  - ../../../argocd/apicurio-registry/
  - ../../../argocd/cert-manager/
  # - ../../../argocd/service-mesh/
  - ../../../argocd/keycloak/
  # - ../../../argocd/vault-secrets/

patches:
  - target:
      version: v1alpha1
      group: argoproj.io
      kind: Application
    patch: |-
      - op: replace
        path: /spec/project
        value: multi-tenant-kafka-cluster-config
  - target:
      version: v1alpha1
      group: argoproj.io
      kind: Application
      name: cluster-config
    patch: |-
      - op: replace
        path: /spec/source/path
        value: cluster-config/profiles/overlays/multi-tenant-kafka
