namespace: openshift-gitops
namePrefix: dev-

resources:
- ../../../applications/demo-weather-interface/
- ../../../applications/ignition-platform/

patches:
  - target:
      version: v1alpha1
      group: argoproj.io
      kind: Application
      name: ignition-platform-app
    patch: |-
      - op: replace
        path: /spec/destination/namespace
        value: dev-demo-weather-interface
      - op: replace
        path: /spec/project
        value: dev-demo-weather-interface
      - op: replace
        path: /spec/source/path
        value: apps/demo-weather-interface/overlays/camel-tahu-demo
