namespace: openshift-gitops
namePrefix: rtr-service-mesh-

resources:
- ../../default/base/
- ../../../applications/streams-kafka/
- ../../../applications/cockroachdb/
- ../../../applications/edb/
- ../../../applications/service-mesh/
- ../../../applications/vault-secrets/

patches:
  - target:
      version: v1alpha1
      group: argoproj.io
      kind: Application
    patch: |-
      - op: replace
        path: /spec/project
        value: rtr-service-mesh-cluster-config
  - target:
      version: v1alpha1
      group: argoproj.io
      kind: Application
      name: cluster-config
    patch: |-
      - op: replace
        path: /spec/source/path
        value: cluster-config/projects/rtr-service-mesh/base
