namespace: openshift-gitops
namePrefix: rtr-service-mesh-

resources:
- ../../default/base/
- ../../../applications/streams-kafka/
- ../../../applications/cockroachdb/
- ../../../applications/edb/
- ../../../applications/service-mesh/
- ../../../applications/vault-secrets/

patches:
- patch: |-
    - op: replace
      path: /spec/project
      value: rtr-service-mesh-cluster-config
  target:
    group: argoproj.io
    kind: Application
    version: v1alpha1
- patch: |-
    - op: replace
      path: /spec/source/path
      value: cluster-config/projects/rtr-service-mesh/base
  target:
    group: argoproj.io
    kind: Application
    name: cluster-config
    version: v1alpha1
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
