apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: kiali-disable-mtls
  namespace: istio-system
spec:
  host: kiali.istio-system.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE