apiVersion: tempo.grafana.com/v1alpha1
kind: TempoMonolithic
metadata:
  name: default
  namespace: tracing-system
spec:
  storage:
    traces:
      backend: pv
      size: 10Gi 
    tls: 
      enabled: false
  jaegerui:
    enabled: true 
    route:
      enabled: true 
