apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-weather-interface-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: demo-weather-interface
    server: https://kubernetes.default.svc
  project: demo-weather-interface
  source:
    path: apps/demo-weather-interface/overlays/dev
    repoURL: https://github.com/ryan-highley/integration-dev-demo-cluster-config
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
