apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: integration-dev-demo
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: Integration Development Demo
  destinations:
    - name: in-cluster
      namespace: '*'
      server: 'https://kubernetes.default.svc'
  sourceRepos:
    - '*'
