namespace: rtr-app-cdb
namePrefix: rtr-app-

resources:
- ../../base
- ../../../../manifests/cockroachdb

patches:
  - target:
      group: project.openshift.io
      version: v1
      kind: Project
      name: cdb
    patch: |-
      - op: add
        path: /metadata/labels/service-mesh-name
        value: basic
  - target:
      group: operators.coreos.com
      version: v1
      kind: Subscription
      name: cockroachdb-certified
    patch: |-
      - op: remove
        path: /metadata/namespace
  - target:
      group: operators.coreos.com
      version: v1
      kind: OperatorGroup
      name: cockroachdb-certified-og
    patch: |-
      - op: add
        path: /spec/targetNamespaces/0
        value: rtr-app-cdb
  - target:
      group: networking.istio.io
      version: v1beta1
      kind: ServiceEntry
      name: cockroachdb-se
    patch: |-
      - op: add
        path: /spec/hosts/0
        value: "*.rtr-app-cdb.rtr-app-cdb.svc"
  - target:
      group: networking.istio.io
      version: v1beta1
      kind: DestinationRule
      name: cockroachdb-dr
    patch: |-
      - op: add
        path: /spec/hosts/0
        value: "*.rtr-app-cdb.rtr-app-cdb.svc"
