namespace: rtr-app-cdb
namePrefix: rtr-app-

resources:
- ../../base
- OperatorGroup_cockroachdb-certified.yaml
- ../../../../manifests/cockroachdb

patches:
  - target:
      group: operators.coreos.com
      version: v1
      kind: Subscription
      name: cockroachdb-certified
    patch: |-
      - op: remove
        path: /metadata/namespace
  # - target:
  #     group: crdb.cockroachlabs.com
  #     version: v1alpha1
  #     kind: CrdbCluster
  #     name: cdb
  #   patch: |-
  #     - op: replace
  #       path: /spec/image/name
  #       value: cockroachdb/cockroach:v23.2.3

