namespace: openshift-operators

resources:
- Subscription_cloud-native-postgresql.yaml
- ConfigMap_postgresql-operator-controller-manager-config.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
