apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cert-manager
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: 'cert-manager'
    server: '*'
  sourceRepos:
  - '*'
