apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: basic
  namespace: istio-system
spec:
  version: v2.6
  security:
    dataPlane:
      mtls: true
    controlPlane:
      mtls: true
    identity:
      type: ThirdParty
      thirdParty:
        audience: istio-ca      
  tracing:
    type: None
    sampling: 10000
  addons:
    kiali:
      enabled: true
      name: kiali
    grafana:
      enabled: true
    prometheus:
      enabled: true