kind: ServiceMeshControlPlane
apiVersion: maistra.io/v2
metadata:
  name: default
spec:
  addons:
    grafana:
      enabled: false
    kiali:
      enabled: true
    prometheus:
      enabled: true
  policy:
    type: Istiod
  telemetry:
    type: Istiod
  version: v2.6