apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops
namePrefix: camel-tahu-demo-

resources:
- ../../default/base/
- ../../../applications/messaging/

patches:
  - target:
      version: v1alpha1
      group: argoproj.io
      kind: Application
    patch: |-
      - op: replace
        path: /spec/project
        value: camel-tahu-demo-cluster-config
